"use strict";

const getRarityRating = {
  "Rare Ultra": -3,
  "Rare Secret": -3,
  "Hyper Rare": -3,
  "Rare Rainbow": -3,
  "Trainer Gallery Rare Holo": -3,
  "Trainer Gallery Rare Holo V": -3,
  "Trainer Gallery Rare Ultra": -3,
  LEGEND: -2,
  "Rare Holo VMAX": -2,
  "Rare Shiny GX": -2,
  "Rare Holo GX": -2,
  VM: -2,
  "Special Illustration Rare": -2,
  "Rare Holo VSTAR": -1,
  "Ultra Rare": -1,
  "Illustration Rare": -1,
  "Rare Holo V": 0,
  V: 0,
  "Double rare": 1,
  "Rare Holo EX": 1,
  "Rare Holo LV.X": 1,
  "Radiant Rare": 1,
  "Rare Shining": 1,
  "Rare Shiny": 1,
  "Amazing Rare": 1,
  Promo: 1,
  "Classic Collection": 2,
  "Rare ACE": 2,
  "Rare BREAK": 2,
  "Rare Holo": 2,
  "Rare Holo Star": 2,
  "Rare Prism Star": 2,
  "Rare Prime": 2,
  Rare: 3,
  Uncommon: 4,
  Common: 5
};

module.exports = getRarityRating;
